import discord
from discord.ext import commands


class GeneralCommands(commands.Cog):

    @commands.command(aliases=['commands','howto', 'bot'])
    async def help(self, ctx):
        embed = discord.Embed(color=discord.Color.dark_purple(), title="Botwell Help")
        embed.add_field(name="Commands", value="Botwell has a variety of commands.\n\n`!botwell thing to search` - Search Bardwell's Youtube Channel for a topic and get 3 links to videos about that topic.\n`!more` - Gives you 3 more links from the list generated by `!botwell`\n`!result 1`,`!result 2`, and `!result 3` - Embeds the Video result you pick.\n`!help` - Shows this help screen!\n`!feedback` - Send in feedback about Botwell", inline=True)
        embed.add_field(name="", value="", inline=False)
        embed.set_footer(text="Made by itsblunty.")
        await ctx.send(embed=embed)

    @commands.command()
    async def ping(self, ctx):
        await ctx.send('Pong!')

    @commands.command()
    async def links(self, ctx):
        await ctx.send("You can find bardwell\'s links at:\nhttps://www.fpvknowitall.com/\nhttps://www.searchfpv.com\nhttps://www.youtube.com/channel/UCX3eufnI7A2I7IkKHZn8KSQ", suppress_embeds=True)


async def setup(bot):
    await bot.add_cog(GeneralCommands(bot))